# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMOB
ICON = icon.png
DESCRIPTION = "Notify Demo Reciever"
COMPRESSED = YES
ARCHIVED = NO

# ----------------------------

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
