# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMOA
ICON = icon.png
DESCRIPTION = "Notify Demo Sender"
COMPRESSED = YES
ARCHIVED = NO

# ----------------------------

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
